/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#2563eb",
        "surface": "#f8fafc",
        "outline-variant": "#e2e8f0",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bcc7de",
        "surface-bright": "#ffffff",
        "inverse-primary": "#adc6ff",
        "on-tertiary-fixed-variant": "#783200",
        "surface-dim": "#f1f5f9",
        "outline": "#64748b",
        "on-tertiary-container": "#fffbff",
        "primary-container": "#eff6ff",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-fixed-dim": "#ffb690",
        "on-surface-variant": "#475569",
        "surface-variant": "#f1f5f9",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#341100",
        "on-secondary-fixed": "#111c2d",
        "surface-container-low": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f8fafc",
        "secondary": "#64748b",
        "on-secondary-container": "#475569",
        "on-error-container": "#93000a",
        "inverse-surface": "#0f172a",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#f1f5f9",
        "secondary-container": "#f1f5f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f8fafc",
        "error-container": "#ffdad6",
        "tertiary-container": "#ea580c",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#0f172a",
        "on-primary-container": "#1e40af",
        "on-primary-fixed": "#001a42",
        "surface-container": "#f8fafc",
        "background": "#f8fafc",
        "surface-tint": "#2563eb",
        "secondary-fixed": "#f1f5f9",
        "on-surface": "#0f172a",
        "tertiary-fixed": "#ffdbca",
        "on-primary-fixed-variant": "#1d4ed8",
        "primary-fixed": "#dbeafe",
        "tertiary": "#c2410c",

        // Professional VS Code Dark Theme Colors
        'vscode-bg': '#1e1e1e',
        'vscode-editor': '#252526',
        'vscode-editor-light': '#2d2d30',
        'vscode-input': '#3c3c3c',
        'vscode-button': '#0e639c',
        'vscode-button-hover': '#1177bb',
        'vscode-focus': '#264f78',
        'vscode-text': '#d4d4d4',
        'vscode-text-muted': '#858585',
        'vscode-text-lighter': '#cccccc',
        'vscode-keyword': '#569cd6',
        'vscode-keyword-alt': '#c586c0',
        'vscode-class': '#4ec9b0',
        'vscode-string': '#ce9178',
        'vscode-comment': '#6a9955',
        'vscode-function': '#dcdcaa',
        'vscode-variable': '#9cdcfe',
        'vscode-tag': '#4ec9b0',
        'vscode-number': '#b5cea8',
        'vscode-operator': '#d4d4d4',
        'vscode-error': '#f48771',
        'vscode-warning': '#dcdcaa',
        'vscode-success': '#4ec9b0',
        'vscode-info': '#569cd6',
      },
      backgroundColor: {
        'vscode-primary': '#1e1e1e',
        'vscode-secondary': '#252526',
        'vscode-tertiary': '#2d2d30',
      },
      textColor: {
        'vscode-primary': '#d4d4d4',
        'vscode-secondary': '#858585',
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      keyframes: {
        'orb-pulse': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.04)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'wave-bar': {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
        'live-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.2)', opacity: '0.8' },
        },
      },
      animation: {
        'orb-pulse': 'orb-pulse 3s infinite ease-in-out',
        'float': 'float 2.5s infinite ease-in-out',
        'wave-bar': 'wave-bar 0.8s infinite ease-in-out',
        'live-pulse': 'live-pulse 1.5s infinite ease-in-out',
      },
    },
  },
  plugins: [],
}
